/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelephonyRouteImport } from './routes/telephony'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IndexRouteImport } from './routes/index'

const TelephonyRoute = TelephonyRouteImport.update({
  id: '/telephony',
  path: '/telephony',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/knowledge': typeof KnowledgeRoute
  '/telephony': typeof TelephonyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/knowledge': typeof KnowledgeRoute
  '/telephony': typeof TelephonyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/knowledge': typeof KnowledgeRoute
  '/telephony': typeof TelephonyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crm' | '/knowledge' | '/telephony'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crm' | '/knowledge' | '/telephony'
  id: '__root__' | '/' | '/crm' | '/knowledge' | '/telephony'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRoute
  KnowledgeRoute: typeof KnowledgeRoute
  TelephonyRoute: typeof TelephonyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telephony': {
      id: '/telephony'
      path: '/telephony'
      fullPath: '/telephony'
      preLoaderRoute: typeof TelephonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRoute,
  KnowledgeRoute: KnowledgeRoute,
  TelephonyRoute: TelephonyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
